### ISSUE TITLE
Run-time MeshXLen and MeshYLen

### ISSUE THREAD

**Issue by m8pple** [POETSII/tinsel#34]
At the moment MeshXLen and MeshYLen are treated as architectural
parameters for a given release, but these are things that we expect to
vary a lot for the "same" architecture. For example, tinsel/master currently
has MeshXLen=3 and MeshYLen=1 as that matches Aesop, but eventually
we'll have a number of different systems with different parameters.

Could/should these parameters be promoted to run-time variables which
are exposed via HostLink? e.g.:
```
int HostLink::getMeshXLen() const;
int HostLink::getMeshYLen() const;
```
on the host side, and:
```
int tinselGetMeshXLen();
int tinselGetMeshYLen();
```
on the thread side? On the thread side these could still back onto TinselMeshXLen
rather than a CSR, but from an API point of view it more clearly indicates intent.

Arguments for:
- It would highlight the fact that these are quite changeable even within
  one architecture, so hopefully avoid incorrect assumptions.
- Managing multiple tinsel repos as I move between 0.2 and 0.3 is a bit complex,
   so I'm then not sure how to support multiple 0.3 variants for different platforms.

Arguments against I can see are:
- It stops you templatising on those parameters, which is quite useful
- Potential for compile-time folding on the compiled tinsel code
- We could just recompile on each machine
- There could be another API layer in front which makes them look like run-time parameters

**Comment by mn416** [comment]
I think the main thrust of this issue has been solved.  Happy to merge a PR that provides the suggested thread side functions.  Will close for now...
