### ISSUE TITLE
Separate boot in hostlink into load and boot commands

### ISSUE THREAD

**Issue by AlexRast** [POETSII/tinsel#62]
As it is, the boot command both loads instruction and data binaries to cores, and starts the boot process for them. 

For the Mothership, we would like load and boot functions to be separate so that a user can preload application code onto target cores for possibly different tasks, then only boot the task they are running at the moment.

Another important use is to allow multithreaded load (to speed load time). The start command, with its barrier function, isn't thread safe, so that can't and shouldn't be multithreaded. But the data/code writes can be multithreaded and if these are separated from the start command then we can run multiple loaders.

**Comment by mn416** [comment]
Hi Alex, looks like this was resolved.  Will close now.  Feel free to repone
