### ISSUE TITLE
Generated config.h has a bad macro line

### ISSUE THREAD

**Issue by AlexRast** [POETSII/tinsel#73]
The config.h file (containing entirely preprocessor macros) generated from config.py has an invalid line. It generates:

#define TinselSharedInstrMem False
or
#define TinselSharedInstrMem True

which means the value will correspond to an unknown variable in C. Line should read

#define TinselSharedInstrMem false
and
#define TinselSharedInstrMem true

**Comment by mn416** [comment]
Hi Alex,

This seems to be fixed now, even though it seems I forgot to link a commit to this issue.  Feel free to reopon...
