### ISSUE TITLE
Run tinsel on other FPGA boards

### ISSUE THREAD

**Issue by yiyuanliu** [POETSII/tinsel#91]
This is a very interesting job, but I think the de5 board used in the project isn't the latest product. The latest fpga boards often have more memory channels or even HBM memory, and 100Gbps network interfaces. Is there any plan to port tinsel to latest fpga boards such as Xilinx U280? Thanks.

**Comment by mn416** [comment]
Hi @yiyuanliu.  Tinsel might be ported to the DE10-Pro (modern Stratix 10 FPGA), but currently there aren't any plans to target Xilinx devices.  Thanks for your interest and your enquiry.
